### ISSUE TITLE
Download Pdf Some Line Issue

### ISSUE THREAD

**Issue by csesuriya** [SagarDNG/ResumeBuilderReactJS#1]
Download Pdf Some Line showing in the pdf.
![Untitled](https://github.com/SagarDNG/ResumeBuilderReactJS/assets/30344091/0e010f50-a6e7-43ff-9309-70aaae52eca0)
[Resume Builder using ReactJS __ SagarDNG.pdf](https://github.com/SagarDNG/ResumeBuilderReactJS/files/15012341/Resume.Builder.using.ReactJS.__.SagarDNG.pdf)

**Comment by csesuriya** [comment]
how to solve this

**Comment by SagarDNG** [comment]
Heyy,
Glad that you used it, 
The problem which you are encountering is simple; it not a line, Its the box shadow of the Resume Content, 
If you don't want it, you can just comment the 9th line here: https://github.com/SagarDNG/ResumeBuilderReactJS/blob/main/src/components/Resume/Resume.module.css

**Comment by SagarDNG** [comment]
I have commented that line and deployed it again
Now, I hope u wont be getting that line xD
